import * as MeteoconsFill from "@/assets/icons/meteocons/fill";
import * as MeteoconsLine from "@/assets/icons/meteocons/line";

export const WMO_CODES_ICONS_FILL_MAP = {
  0: { day: MeteoconsFill.ClearDay, night: MeteoconsFill.ClearNight },
  1: { day: MeteoconsFill.ClearDay, night: MeteoconsFill.ClearNight },
  2: {
    day: MeteoconsFill.PartlyCloudyDay,
    night: MeteoconsFill.PartlyCloudyNight,
  },
  3: { day: MeteoconsFill.Overcast, night: MeteoconsFill.Overcast },
  45: { day: MeteoconsFill.FogDay, night: MeteoconsFill.FogNight },
  48: { day: MeteoconsFill.FogDay, night: MeteoconsFill.FogNight },
  51: { day: MeteoconsFill.Drizzle, night: MeteoconsFill.Drizzle },
  53: { day: MeteoconsFill.Drizzle, night: MeteoconsFill.Drizzle },
  55: { day: MeteoconsFill.Drizzle, night: MeteoconsFill.Drizzle },
  56: { day: MeteoconsFill.Sleet, night: MeteoconsFill.Sleet },
  57: { day: MeteoconsFill.Sleet, night: MeteoconsFill.Sleet },
  61: { day: MeteoconsFill.Rain, night: MeteoconsFill.Rain },
  63: { day: MeteoconsFill.Rain, night: MeteoconsFill.Rain },
  65: { day: MeteoconsFill.Rain, night: MeteoconsFill.Rain },
  66: { day: MeteoconsFill.Sleet, night: MeteoconsFill.Sleet },
  67: { day: MeteoconsFill.Sleet, night: MeteoconsFill.Sleet },
  71: { day: MeteoconsFill.Snow, night: MeteoconsFill.Snow },
  73: { day: MeteoconsFill.Snow, night: MeteoconsFill.Snow },
  75: { day: MeteoconsFill.Snow, night: MeteoconsFill.Snow },
  77: { day: MeteoconsFill.Snowflake, night: MeteoconsFill.Snowflake },
  80: {
    day: MeteoconsFill.PartlyCloudyDayRain,
    night: MeteoconsFill.PartlyCloudyNightRain,
  },
  81: {
    day: MeteoconsFill.PartlyCloudyDayRain,
    night: MeteoconsFill.PartlyCloudyNightRain,
  },
  82: { day: MeteoconsFill.Rain, night: MeteoconsFill.Rain },
  85: {
    day: MeteoconsFill.PartlyCloudyDaySnow,
    night: MeteoconsFill.PartlyCloudyNightSnow,
  },
  86: { day: MeteoconsFill.Snow, night: MeteoconsFill.Snow },
  95: { day: MeteoconsFill.Thunderstorms, night: MeteoconsFill.Thunderstorms },
  96: {
    day: MeteoconsFill.ThunderstormsRain,
    night: MeteoconsFill.ThunderstormsRain,
  },
  99: {
    day: MeteoconsFill.ThunderstormsRain,
    night: MeteoconsFill.ThunderstormsRain,
  },
} as const;

export const WMO_CODES_ICONS_LINE_MAP = {
  0: { day: MeteoconsLine.ClearDay, night: MeteoconsLine.ClearNight },
  1: { day: MeteoconsLine.ClearDay, night: MeteoconsLine.ClearNight },
  2: {
    day: MeteoconsLine.PartlyCloudyDay,
    night: MeteoconsLine.PartlyCloudyNight,
  },
  3: { day: MeteoconsLine.Overcast, night: MeteoconsLine.Overcast },
  45: { day: MeteoconsLine.FogDay, night: MeteoconsLine.FogNight },
  48: { day: MeteoconsLine.FogDay, night: MeteoconsLine.FogNight },
  51: { day: MeteoconsLine.Drizzle, night: MeteoconsLine.Drizzle },
  53: { day: MeteoconsLine.Drizzle, night: MeteoconsLine.Drizzle },
  55: { day: MeteoconsLine.Drizzle, night: MeteoconsLine.Drizzle },
  56: { day: MeteoconsLine.Sleet, night: MeteoconsLine.Sleet },
  57: { day: MeteoconsLine.Sleet, night: MeteoconsLine.Sleet },
  61: { day: MeteoconsLine.Rain, night: MeteoconsLine.Rain },
  63: { day: MeteoconsLine.Rain, night: MeteoconsLine.Rain },
  65: { day: MeteoconsLine.Rain, night: MeteoconsLine.Rain },
  66: { day: MeteoconsLine.Sleet, night: MeteoconsLine.Sleet },
  67: { day: MeteoconsLine.Sleet, night: MeteoconsLine.Sleet },
  71: { day: MeteoconsLine.Snow, night: MeteoconsLine.Snow },
  73: { day: MeteoconsLine.Snow, night: MeteoconsLine.Snow },
  75: { day: MeteoconsLine.Snow, night: MeteoconsLine.Snow },
  77: { day: MeteoconsLine.Snowflake, night: MeteoconsLine.Snowflake },
  80: {
    day: MeteoconsLine.PartlyCloudyDayRain,
    night: MeteoconsLine.PartlyCloudyNightRain,
  },
  81: {
    day: MeteoconsLine.PartlyCloudyDayRain,
    night: MeteoconsLine.PartlyCloudyNightRain,
  },
  82: { day: MeteoconsLine.Rain, night: MeteoconsLine.Rain },
  85: {
    day: MeteoconsLine.PartlyCloudyDaySnow,
    night: MeteoconsLine.PartlyCloudyNightSnow,
  },
  86: { day: MeteoconsLine.Snow, night: MeteoconsLine.Snow },
  95: { day: MeteoconsLine.Thunderstorms, night: MeteoconsLine.Thunderstorms },
  96: {
    day: MeteoconsLine.ThunderstormsRain,
    night: MeteoconsLine.ThunderstormsRain,
  },
  99: {
    day: MeteoconsLine.ThunderstormsRain,
    night: MeteoconsLine.ThunderstormsRain,
  },
} as const;

export const WMO_CODES_MAP = {
  0: "Clear sky",
  1: "Mainly clear",
  2: "Partly cloudy",
  3: "Overcast",
  45: "Fog",
  48: "Depositing rime fog",
  51: "Light drizzle",
  53: "Moderate drizzle",
  55: "Dense drizzle",
  56: "Light freezing drizzle",
  57: "Dense freezing drizzle",
  61: "Slight rain",
  63: "Moderate rain",
  65: "Heavy rain",
  66: "Light freezing rain",
  67: "Heavy freezing rain",
  71: "Slight snow fall",
  73: "Moderate snow fall",
  75: "Heavy snow fall",
  77: "Snow grains",
  80: "Slight rain showers",
  81: "Moderate rain showers",
  82: "Violent rain showers",
  85: "Slight snow showers",
  86: "Heavy snow showers",
  95: "Thunderstorm",
  96: "Thunderstorm with slight hail",
  99: "Thunderstorm with heavy hail",
} as const;

export const WMO_RAIN_CODES_MAP = {
  51: WMO_CODES_MAP[51],
  53: WMO_CODES_MAP[53],
  55: WMO_CODES_MAP[55],
  56: WMO_CODES_MAP[56],
  57: WMO_CODES_MAP[57],
  61: WMO_CODES_MAP[61],
  63: WMO_CODES_MAP[63],
  65: WMO_CODES_MAP[65],
  66: WMO_CODES_MAP[66],
  67: WMO_CODES_MAP[67],
  80: WMO_CODES_MAP[80],
  81: WMO_CODES_MAP[81],
  82: WMO_CODES_MAP[82],
  95: WMO_CODES_MAP[95],
  96: WMO_CODES_MAP[96],
  99: WMO_CODES_MAP[99],
} as const;

export const WMO_SNOW_CODES_MAP = {
  71: WMO_CODES_MAP[71],
  73: WMO_CODES_MAP[73],
  75: WMO_CODES_MAP[75],
  77: WMO_CODES_MAP[77],
  85: WMO_CODES_MAP[85],
  86: WMO_CODES_MAP[86],
} as const;
