import * as MeteoconsFill from "@/assets/icons/meteocons/fill";
import * as MeteoconsLine from "@/assets/icons/meteocons/line";

export const WMO_CODES_MAP = {
  0: "Clear sky",
  1: "Mainly clear",
  2: "Partly cloudy",
  3: "Overcast",
  45: "Fog",
  48: "Depositing rime fog",
  51: "Light drizzle",
  53: "Moderate drizzle",
  55: "Dense drizzle",
  56: "Light freezing drizzle",
  57: "Dense freezing drizzle",
  61: "Slight rain",
  63: "Moderate rain",
  65: "Heavy rain",
  66: "Light freezing rain",
  67: "Heavy freezing rain",
  71: "Slight snow fall",
  73: "Moderate snow fall",
  75: "Heavy snow fall",
  77: "Snow grains",
  80: "Slight rain showers",
  81: "Moderate rain showers",
  82: "Violent rain showers",
  85: "Slight snow showers",
  86: "Heavy snow showers",
  95: "Thunderstorm",
  96: "Thunderstorm with slight hail",
  99: "Thunderstorm with heavy hail",
} as const;

export const WMO_RAIN_CODES_MAP = {
  51: WMO_CODES_MAP[51],
  53: WMO_CODES_MAP[53],
  55: WMO_CODES_MAP[55],
  56: WMO_CODES_MAP[56],
  57: WMO_CODES_MAP[57],
  61: WMO_CODES_MAP[61],
  63: WMO_CODES_MAP[63],
  65: WMO_CODES_MAP[65],
  66: WMO_CODES_MAP[66],
  67: WMO_CODES_MAP[67],
  80: WMO_CODES_MAP[80],
  81: WMO_CODES_MAP[81],
  82: WMO_CODES_MAP[82],
  95: WMO_CODES_MAP[95],
  96: WMO_CODES_MAP[96],
  99: WMO_CODES_MAP[99],
} as const;

export const WMO_SNOW_CODES_MAP = {
  71: WMO_CODES_MAP[71],
  73: WMO_CODES_MAP[73],
  75: WMO_CODES_MAP[75],
  77: WMO_CODES_MAP[77],
  85: WMO_CODES_MAP[85],
  86: WMO_CODES_MAP[86],
} as const;

export const WMO_CODES_DAY_ICONS_FILL_MAP = {
  0: MeteoconsFill.ClearDay,
  1: MeteoconsFill.ClearDay,
  2: MeteoconsFill.PartlyCloudyDay,
  3: MeteoconsFill.Overcast,
  45: MeteoconsFill.FogDay,
  48: MeteoconsFill.FogDay,
  51: MeteoconsFill.Drizzle,
  53: MeteoconsFill.Drizzle,
  55: MeteoconsFill.Drizzle,
  56: MeteoconsFill.Sleet,
  57: MeteoconsFill.Sleet,
  61: MeteoconsFill.Rain,
  63: MeteoconsFill.Rain,
  65: MeteoconsFill.Rain,
  66: MeteoconsFill.Sleet,
  67: MeteoconsFill.Sleet,
  71: MeteoconsFill.Snow,
  73: MeteoconsFill.Snow,
  75: MeteoconsFill.Snow,
  77: MeteoconsFill.Snowflake,
  80: MeteoconsFill.PartlyCloudyDayRain,
  81: MeteoconsFill.PartlyCloudyDayRain,
  82: MeteoconsFill.Rain,
  85: MeteoconsFill.PartlyCloudyDaySnow,
  86: MeteoconsFill.Snow,
  95: MeteoconsFill.Thunderstorms,
  96: MeteoconsFill.ThunderstormsRain,
  99: MeteoconsFill.ThunderstormsRain,
} as const;

export const WMO_CODES_DAY_ICONS_LINE_MAP = {
  0: MeteoconsLine.ClearDay,
  1: MeteoconsLine.ClearDay,
  2: MeteoconsLine.PartlyCloudyDay,
  3: MeteoconsLine.Overcast,
  45: MeteoconsLine.FogDay,
  48: MeteoconsLine.FogDay,
  51: MeteoconsLine.Drizzle,
  53: MeteoconsLine.Drizzle,
  55: MeteoconsLine.Drizzle,
  56: MeteoconsLine.Sleet,
  57: MeteoconsLine.Sleet,
  61: MeteoconsLine.Rain,
  63: MeteoconsLine.Rain,
  65: MeteoconsLine.Rain,
  66: MeteoconsLine.Sleet,
  67: MeteoconsLine.Sleet,
  71: MeteoconsLine.Snow,
  73: MeteoconsLine.Snow,
  75: MeteoconsLine.Snow,
  77: MeteoconsLine.Snowflake,
  80: MeteoconsLine.PartlyCloudyDayRain,
  81: MeteoconsLine.PartlyCloudyDayRain,
  82: MeteoconsLine.Rain,
  85: MeteoconsLine.PartlyCloudyDaySnow,
  86: MeteoconsLine.Snow,
  95: MeteoconsLine.Thunderstorms,
  96: MeteoconsLine.ThunderstormsRain,
  99: MeteoconsLine.ThunderstormsRain,
} as const;

export const WMO_CODES_NIGHT_ICONS_FILL_MAP = {
  0: MeteoconsFill.ClearNight,
  1: MeteoconsFill.ClearNight,
  2: MeteoconsFill.PartlyCloudyNight,
  3: MeteoconsFill.Overcast,
  45: MeteoconsFill.FogNight,
  48: MeteoconsFill.FogNight,
  51: MeteoconsFill.Drizzle,
  53: MeteoconsFill.Drizzle,
  55: MeteoconsFill.Drizzle,
  56: MeteoconsFill.Sleet,
  57: MeteoconsFill.Sleet,
  61: MeteoconsFill.Rain,
  63: MeteoconsFill.Rain,
  65: MeteoconsFill.Rain,
  66: MeteoconsFill.Sleet,
  67: MeteoconsFill.Sleet,
  71: MeteoconsFill.Snow,
  73: MeteoconsFill.Snow,
  75: MeteoconsFill.Snow,
  77: MeteoconsFill.Snowflake,
  80: MeteoconsFill.PartlyCloudyNightRain,
  81: MeteoconsFill.PartlyCloudyNightRain,
  82: MeteoconsFill.Rain,
  85: MeteoconsFill.PartlyCloudyNightSnow,
  86: MeteoconsFill.Snow,
  95: MeteoconsFill.Thunderstorms,
  96: MeteoconsFill.ThunderstormsRain,
  99: MeteoconsFill.ThunderstormsRain,
} as const;

export const WMO_CODES_NIGHT_ICONS_LINE_MAP = {
  0: MeteoconsLine.ClearNight,
  1: MeteoconsLine.ClearNight,
  2: MeteoconsLine.PartlyCloudyNight,
  3: MeteoconsLine.Overcast,
  45: MeteoconsLine.FogNight,
  48: MeteoconsLine.FogNight,
  51: MeteoconsLine.Drizzle,
  53: MeteoconsLine.Drizzle,
  55: MeteoconsLine.Drizzle,
  56: MeteoconsLine.Sleet,
  57: MeteoconsLine.Sleet,
  61: MeteoconsLine.Rain,
  63: MeteoconsLine.Rain,
  65: MeteoconsLine.Rain,
  66: MeteoconsLine.Sleet,
  67: MeteoconsLine.Sleet,
  71: MeteoconsLine.Snow,
  73: MeteoconsLine.Snow,
  75: MeteoconsLine.Snow,
  77: MeteoconsLine.Snowflake,
  80: MeteoconsLine.PartlyCloudyNightRain,
  81: MeteoconsLine.PartlyCloudyNightRain,
  82: MeteoconsLine.Rain,
  85: MeteoconsLine.PartlyCloudyNightSnow,
  86: MeteoconsLine.Snow,
  95: MeteoconsLine.Thunderstorms,
  96: MeteoconsLine.ThunderstormsRain,
  99: MeteoconsLine.ThunderstormsRain,
} as const;
