// Automatically generated by scripts/generate-tailwind-maps.mjs
// DO NOT EDIT MANUALLY

export const BUTTON_SIZE_MAP = {
  xs: {
    ["base"]: "btn-xs",
    ["sm"]: "sm:btn-xs",
    ["md"]: "md:btn-xs",
    ["lg"]: "lg:btn-xs",
    ["xl"]: "xl:btn-xs",
    ["2xl"]: "2xl:btn-xs",
  },
  sm: {
    ["base"]: "btn-sm",
    ["sm"]: "sm:btn-sm",
    ["md"]: "md:btn-sm",
    ["lg"]: "lg:btn-sm",
    ["xl"]: "xl:btn-sm",
    ["2xl"]: "2xl:btn-sm",
  },
  md: {
    ["base"]: "btn-md",
    ["sm"]: "sm:btn-md",
    ["md"]: "md:btn-md",
    ["lg"]: "lg:btn-md",
    ["xl"]: "xl:btn-md",
    ["2xl"]: "2xl:btn-md",
  },
  lg: {
    ["base"]: "btn-lg",
    ["sm"]: "sm:btn-lg",
    ["md"]: "md:btn-lg",
    ["lg"]: "lg:btn-lg",
    ["xl"]: "xl:btn-lg",
    ["2xl"]: "2xl:btn-lg",
  },
  xl: {
    ["base"]: "btn-xl",
    ["sm"]: "sm:btn-xl",
    ["md"]: "md:btn-xl",
    ["lg"]: "lg:btn-xl",
    ["xl"]: "xl:btn-xl",
    ["2xl"]: "2xl:btn-xl",
  },
} as const;

export const BUTTON_COLOR_MAP = {
  neutral: {
    ["base"]: "btn-neutral",
    ["sm"]: "sm:btn-neutral",
    ["md"]: "md:btn-neutral",
    ["lg"]: "lg:btn-neutral",
    ["xl"]: "xl:btn-neutral",
    ["2xl"]: "2xl:btn-neutral",
  },
  primary: {
    ["base"]: "btn-primary",
    ["sm"]: "sm:btn-primary",
    ["md"]: "md:btn-primary",
    ["lg"]: "lg:btn-primary",
    ["xl"]: "xl:btn-primary",
    ["2xl"]: "2xl:btn-primary",
  },
  secondary: {
    ["base"]: "btn-secondary",
    ["sm"]: "sm:btn-secondary",
    ["md"]: "md:btn-secondary",
    ["lg"]: "lg:btn-secondary",
    ["xl"]: "xl:btn-secondary",
    ["2xl"]: "2xl:btn-secondary",
  },
  accent: {
    ["base"]: "btn-accent",
    ["sm"]: "sm:btn-accent",
    ["md"]: "md:btn-accent",
    ["lg"]: "lg:btn-accent",
    ["xl"]: "xl:btn-accent",
    ["2xl"]: "2xl:btn-accent",
  },
  info: {
    ["base"]: "btn-info",
    ["sm"]: "sm:btn-info",
    ["md"]: "md:btn-info",
    ["lg"]: "lg:btn-info",
    ["xl"]: "xl:btn-info",
    ["2xl"]: "2xl:btn-info",
  },
  success: {
    ["base"]: "btn-success",
    ["sm"]: "sm:btn-success",
    ["md"]: "md:btn-success",
    ["lg"]: "lg:btn-success",
    ["xl"]: "xl:btn-success",
    ["2xl"]: "2xl:btn-success",
  },
  warning: {
    ["base"]: "btn-warning",
    ["sm"]: "sm:btn-warning",
    ["md"]: "md:btn-warning",
    ["lg"]: "lg:btn-warning",
    ["xl"]: "xl:btn-warning",
    ["2xl"]: "2xl:btn-warning",
  },
  error: {
    ["base"]: "btn-error",
    ["sm"]: "sm:btn-error",
    ["md"]: "md:btn-error",
    ["lg"]: "lg:btn-error",
    ["xl"]: "xl:btn-error",
    ["2xl"]: "2xl:btn-error",
  },
} as const;

export const BUTTON_VARIANT_MAP = {
  soft: {
    ["base"]: "btn-soft",
    ["sm"]: "sm:btn-soft",
    ["md"]: "md:btn-soft",
    ["lg"]: "lg:btn-soft",
    ["xl"]: "xl:btn-soft",
    ["2xl"]: "2xl:btn-soft",
  },
  outline: {
    ["base"]: "btn-outline",
    ["sm"]: "sm:btn-outline",
    ["md"]: "md:btn-outline",
    ["lg"]: "lg:btn-outline",
    ["xl"]: "xl:btn-outline",
    ["2xl"]: "2xl:btn-outline",
  },
  dash: {
    ["base"]: "btn-dash",
    ["sm"]: "sm:btn-dash",
    ["md"]: "md:btn-dash",
    ["lg"]: "lg:btn-dash",
    ["xl"]: "xl:btn-dash",
    ["2xl"]: "2xl:btn-dash",
  },
  neutral: {
    ["base"]: "btn-neutral",
    ["sm"]: "sm:btn-neutral",
    ["md"]: "md:btn-neutral",
    ["lg"]: "lg:btn-neutral",
    ["xl"]: "xl:btn-neutral",
    ["2xl"]: "2xl:btn-neutral",
  },
  active: {
    ["base"]: "btn-active",
    ["sm"]: "sm:btn-active",
    ["md"]: "md:btn-active",
    ["lg"]: "lg:btn-active",
    ["xl"]: "xl:btn-active",
    ["2xl"]: "2xl:btn-active",
  },
  ghost: {
    ["base"]: "btn-ghost",
    ["sm"]: "sm:btn-ghost",
    ["md"]: "md:btn-ghost",
    ["lg"]: "lg:btn-ghost",
    ["xl"]: "xl:btn-ghost",
    ["2xl"]: "2xl:btn-ghost",
  },
  link: {
    ["base"]: "btn-link",
    ["sm"]: "sm:btn-link",
    ["md"]: "md:btn-link",
    ["lg"]: "lg:btn-link",
    ["xl"]: "xl:btn-link",
    ["2xl"]: "2xl:btn-link",
  },
} as const;

export const BUTTON_SHAPE_MAP = {
  circle: {
    ["base"]: "btn-circle",
    ["sm"]: "sm:btn-circle",
    ["md"]: "md:btn-circle",
    ["lg"]: "lg:btn-circle",
    ["xl"]: "xl:btn-circle",
    ["2xl"]: "2xl:btn-circle",
  },
  square: {
    ["base"]: "btn-square",
    ["sm"]: "sm:btn-square",
    ["md"]: "md:btn-square",
    ["lg"]: "lg:btn-square",
    ["xl"]: "xl:btn-square",
    ["2xl"]: "2xl:btn-square",
  },
} as const;

export const BUTTON_DISPLAY_MAP = {
  wide: {
    ["base"]: "btn-wide",
    ["sm"]: "sm:btn-wide",
    ["md"]: "md:btn-wide",
    ["lg"]: "lg:btn-wide",
    ["xl"]: "xl:btn-wide",
    ["2xl"]: "2xl:btn-wide",
  },
  block: {
    ["base"]: "btn-block",
    ["sm"]: "sm:btn-block",
    ["md"]: "md:btn-block",
    ["lg"]: "lg:btn-block",
    ["xl"]: "xl:btn-block",
    ["2xl"]: "2xl:btn-block",
  },
} as const;
