/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MapsRouteImport } from './routes/maps'
import { Route as homeIndexRouteImport } from './routes/(home)/index'
import { Route as WeatherCountryProvinceCityPeriodRouteImport } from './routes/weather.$country.$province.$city.$period'

const MapsRoute = MapsRouteImport.update({
  id: '/maps',
  path: '/maps',
  getParentRoute: () => rootRouteImport,
} as any)
const homeIndexRoute = homeIndexRouteImport.update({
  id: '/(home)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WeatherCountryProvinceCityPeriodRoute =
  WeatherCountryProvinceCityPeriodRouteImport.update({
    id: '/weather/$country/$province/$city/$period',
    path: '/weather/$country/$province/$city/$period',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/maps': typeof MapsRoute
  '/': typeof homeIndexRoute
  '/weather/$country/$province/$city/$period': typeof WeatherCountryProvinceCityPeriodRoute
}
export interface FileRoutesByTo {
  '/maps': typeof MapsRoute
  '/': typeof homeIndexRoute
  '/weather/$country/$province/$city/$period': typeof WeatherCountryProvinceCityPeriodRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/maps': typeof MapsRoute
  '/(home)/': typeof homeIndexRoute
  '/weather/$country/$province/$city/$period': typeof WeatherCountryProvinceCityPeriodRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/maps' | '/' | '/weather/$country/$province/$city/$period'
  fileRoutesByTo: FileRoutesByTo
  to: '/maps' | '/' | '/weather/$country/$province/$city/$period'
  id:
    | '__root__'
    | '/maps'
    | '/(home)/'
    | '/weather/$country/$province/$city/$period'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MapsRoute: typeof MapsRoute
  homeIndexRoute: typeof homeIndexRoute
  WeatherCountryProvinceCityPeriodRoute: typeof WeatherCountryProvinceCityPeriodRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/maps': {
      id: '/maps'
      path: '/maps'
      fullPath: '/maps'
      preLoaderRoute: typeof MapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/': {
      id: '/(home)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof homeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weather/$country/$province/$city/$period': {
      id: '/weather/$country/$province/$city/$period'
      path: '/weather/$country/$province/$city/$period'
      fullPath: '/weather/$country/$province/$city/$period'
      preLoaderRoute: typeof WeatherCountryProvinceCityPeriodRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  MapsRoute: MapsRoute,
  homeIndexRoute: homeIndexRoute,
  WeatherCountryProvinceCityPeriodRoute: WeatherCountryProvinceCityPeriodRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
