/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MapsRouteImport } from './routes/maps'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WeatherCountryProvinceCityPeriodCoordsRouteImport } from './routes/weather.$country.$province.$city.$period.$coords'

const MapsRoute = MapsRouteImport.update({
  id: '/maps',
  path: '/maps',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WeatherCountryProvinceCityPeriodCoordsRoute =
  WeatherCountryProvinceCityPeriodCoordsRouteImport.update({
    id: '/weather/$country/$province/$city/$period/$coords',
    path: '/weather/$country/$province/$city/$period/$coords',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/maps': typeof MapsRoute
  '/weather/$country/$province/$city/$period/$coords': typeof WeatherCountryProvinceCityPeriodCoordsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/maps': typeof MapsRoute
  '/weather/$country/$province/$city/$period/$coords': typeof WeatherCountryProvinceCityPeriodCoordsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/maps': typeof MapsRoute
  '/weather/$country/$province/$city/$period/$coords': typeof WeatherCountryProvinceCityPeriodCoordsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/maps' | '/weather/$country/$province/$city/$period/$coords'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/maps' | '/weather/$country/$province/$city/$period/$coords'
  id:
    | '__root__'
    | '/'
    | '/maps'
    | '/weather/$country/$province/$city/$period/$coords'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MapsRoute: typeof MapsRoute
  WeatherCountryProvinceCityPeriodCoordsRoute: typeof WeatherCountryProvinceCityPeriodCoordsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/maps': {
      id: '/maps'
      path: '/maps'
      fullPath: '/maps'
      preLoaderRoute: typeof MapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weather/$country/$province/$city/$period/$coords': {
      id: '/weather/$country/$province/$city/$period/$coords'
      path: '/weather/$country/$province/$city/$period/$coords'
      fullPath: '/weather/$country/$province/$city/$period/$coords'
      preLoaderRoute: typeof WeatherCountryProvinceCityPeriodCoordsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MapsRoute: MapsRoute,
  WeatherCountryProvinceCityPeriodCoordsRoute:
    WeatherCountryProvinceCityPeriodCoordsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
